dist: trusty
sudo: false
language: node_js
node_js:
  - "10"
  - "8"

before_install:
  - bash ci/install-capnproto.sh
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/opt/bin:$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile

script: yarn run ci

cache:
  yarn: true
  directories:
    - node_modules
    - js-examples/node_modules
    - packages/capnp-ts/node_modules
    - packages/capnpc-ts/node_modules
    - packages/capnpc-js/node_modules
